# Generated by Django 6.0.2 on 2026-02-26 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('total_hours_required', models.FloatField(help_text='Total hours required for internship')),
                ('total_hours_logged', models.FloatField(default=0, help_text='Total hours recorded so far')),
                ('supervisor_name', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('am_in', models.TimeField(blank=True, null=True)),
                ('am_out', models.TimeField(blank=True, null=True)),
                ('pm_in', models.TimeField(blank=True, null=True)),
                ('pm_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.FloatField(default=0, help_text='Total hours worked this day')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.internship')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('internship', 'date')},
            },
        ),
    ]
