# Generated by Django 6.0.2 on 2026-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimerecord',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytimerecord',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
