# Generated by Django 6.0.2 on 2026-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_dailytimerecord_is_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimerecord',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
