# Generated by Django 6.0.2 on 2026-03-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_dailytimerecord_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='total_hours_logged',
        ),
    ]
