# Generated by Django 6.0.2 on 2026-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_internship_total_hours_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimerecord',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
